service: sample-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  memorySize: 128
functions:
  app-api:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any
